<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="resume.xsl"?>

<!DOCTYPE resume [
<!ELEMENT resume (basic_info,education,academic_acievements,skill_set,soft_skill,past_experience,personal_interest)>
<!ELEMENT basic_info (name,gender,dob,age,email,number)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT education (qualification+)>
<!ELEMENT qualification (name,institute,board,year,result)>
<!ELEMENT institute (#PCDATA)>
<!ELEMENT board (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT result (#PCDATA)>
<!ELEMENT academic_acievements (achievement+)>
<!ELEMENT achievement (description)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT skill_set (basic_skill,proficient_skill,specialised_skill)>
<!ELEMENT basic_skill (#PCDATA)>
<!ELEMENT proficient_skill (#PCDATA)>
<!ELEMENT specialised_skill (#PCDATA)>
<!ELEMENT soft_skill (skill+)>
<!ELEMENT skill (description)>
<!ELEMENT past_experience (experience+)>
<!ELEMENT experience (description)>
<!ELEMENT personal_interest (#PCDATA)>
]>

<resume>
  <basic_info>
    <name>Cyril Kunjumon Daniel</name>
    <gender>Male</gender>
    <dob>September 20 2001</dob>
    <age>19</age>
    <email>ckd853@uowmail.edu.au</email>
    <number>+971502313483</number>
  </basic_info>
  <education>
    <qualification>
      <name>Higher Secondary School Certificate</name>
      <institute>Our Own High School</institute>
      <board>CBSE(Central Board of Secondary Education)</board>
      <year>2019</year>
      <result>94%</result>
    </qualification>
    <qualification>
      <name>Senior School Certificate</name>
      <institute>Our Own High School</institute>
      <board>CBSE(Central Board of Secondary Education)</board>
      <year>2017</year>
      <result>CGPA 10</result>
    </qualification>
  </education>
  <academic_acievements>
    <achievement><description>Awarded for attaining the highest grade in Senior School</description></achievement>
    <achievement><description>Awarded for attaining the highest grade in Mathematics in Higher Secondary School</description></achievement>
    <achievement><description>Received other awards for sports, quiz competitions, cooking and spelling bee</description></achievement>
  </academic_acievements>
  <skill_set>
    <basic_skill>Basic skills in photo and video editing, along with the ability to use various Microsoft utilities such as MS Word, MS PowerPoint, MS Excel, MS Access, etc.</basic_skill>
    <proficient_skill>Highly proficient in programming languages such as C++, JAVA, Python and web - page development programming languages including HTML, CSS, XML, JAVAScript, etc. Also proficient in mathematics, design of algorithms as well as in SQL programming for databases.</proficient_skill>
    <specialised_skill>Specialised in programming functional and apt solutions with JAVA and C++.</specialised_skill>
  </skill_set>
  <soft_skill>
    <skill><description>Fluent in English as a spoken and written language</description></skill>
    <skill><description>Works well in a team and very cooperative</description></skill>
    <skill><description>Loves new challenges and admires learning new things</description></skill>
    <skill><description>Handles pressure well, always motivated and determined to complete any task at hand</description></skill>
  </soft_skill>
  <past_experience>
    <experience><description>Attended the AI camp conducted by Microsoft</description></experience>
    <experience><description>Took part in the Duke of Edinburgh's Award, and thereby took part in various events that involved volunteering and charity</description></experience>
    <experience><description>Attended workshops on Cloud Computing</description></experience>
  </past_experience>
  <personal_interest>
    Keeping aside the academics, I find enjoyment in other activities like travelling, watching and playing football, wrestling, cycling and badminton. Other interests include reading and cooking.
  </personal_interest>
</resume>
